# -*- coding: utf-8 -*-
"""
Created on Tue Apr 14 16:14:54 2020

@author: JP
"""

import pandas as pd

m_data = {
    430: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 17,
          'Temp': 30,
          'Preamp': False,
          'Rate': 8,
          'Time': 600,
          'Dir': 'Down',
          'Limit': .2,
          'dB': .01,
          'timeconstant': .1,
          },
    431: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 17,
          'Temp': 30,
          'Preamp': False,
          'Rate': 8,
          'Time': 600,
          'Dir': 'Up',
          'Limit': .2,
          'dB': .01,
          'timeconstant': .1,
          },
    432: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 17,
          'Temp': 30,
          'Preamp': True,
          'Rate': 16,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .0025,
          'Error': True,
          'timeconstant': .1,
          },
    433: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': True,
          'Rate': 16,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .002,
          'timeconstant': .1,
          },
    434: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': True,
          'Rate': 32,
          'Time': 512,
          'Dir': 'Up',
          'Limit': .2,
          'dB': .02,
          'timeconstant': .1,
          },
    435: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': True,
          'Rate': 16,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    436: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': True,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .2,
          'dB': .005,
          'timeconstant': .1,
          },
    437: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': False,
          'Rate': 8,
          'Time': 768,
          'Dir': 'Up',
          'Limit': .15,
          'dB': .005,
          'timeconstant': .1,
          },
    438: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': False,
          'Rate': 4,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .01,
          'timeconstant': .1,
          },
    439: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': False,
          'Rate': 16,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    440: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': False,
          'Rate': 32,
          'Time': 512,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    441: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': False,
          'Rate': 32,
          'Time': 512,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    442: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 30,
          'Preamp': False,
          'Rate': 4,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    443: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 20,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'Error': True,
          'timeconstant': .1,
          },
    444: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 20,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .005,
          'Error': True,
          'timeconstant': .1,
          },
    445: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 10,
          'Preamp': False,
          'Rate': 2,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'Error': True,
          'timeconstant': .1,
          },
    446: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    447: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .1,
          },
    448: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 4,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'Error': True,
          'timeconstant': .3,
          },
    449: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 4,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .005,
          'Error': True,
          'timeconstant': .3,
          },
    450: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .3,
          },
    451: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .005,
          'timeconstant': .3,
          },
    452: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .3,
          'dB': .015,
          'timeconstant': .1,
          },
    453: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .3,
          'dB': .015,
          'timeconstant': .1,
          },
    454: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .15,
          'dB': .005,
          'Error': True,
          'timeconstant': .1,
          },
    455: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .15,
          'dB': .005,
          'timeconstant': .1,
          },
    456: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'STATIC',
          'Limit': 0,
          'dB': 0,
          'timeconstant': .1,
          },
    458: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    459: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    460: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'Error': True,
          'timeconstant': .1,
          },
    461: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    462: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    463: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    464: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 2048,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    466: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .03,
          },
    467: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .03,
          },
    468: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .03,
          },
    469: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .03,
          },
    470: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .01,
          },
    471: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .01,
          },
    472: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1800,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    473: {'Struct': 'Plusses',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1800,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    474: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    475: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    476: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .03,
          },
    477: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .03,
          },
    478: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    479: {'Struct': 'Empty',
          'Angle': 80,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    480: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    481: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    482: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    483: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    484: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    485: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 2.5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .1,
          'dB': .05,
          'timeconstant': .1,
          },
    486: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .1,
          },
    487: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .1,
          },
    488: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .03,
          },
    489: {'Struct': 'Plusses',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .03,
          },
    490: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .1,
          },
    491: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .1,
          },
    492: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Down',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .03,
          },
    493: {'Struct': 'Empty',
          'Angle': 45,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .2,
          'dB': .1,
          'timeconstant': .03,
          },
    494: {'Struct': 'Empty',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '200/150/100/50',
          'Error': True,
          'timeconstant': .003,
          },
    495: {'Struct': 'Empty',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '20/15/10/5',
          'Error': True,
          'timeconstant': .003,
          },
    496: {'Struct': 'Empty',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Time': 1024,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '2/1.5/1',
          'Error': True,
          'timeconstant': .003,
          },
    497: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '20/15/10/5/2.5/1',
          'timeconstant': .003,
          },
    498: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': '/'.join([str(_/2) for _ in range(1,11)]),
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .1,
          'SR': '5.9',
          'timeconstant': .003,
          },
    499: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': '/'.join([str(_/2) for _ in range(1,11)]),
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .1,
          'SR': '5.9',
          'timeconstant': .003,
          },
    500: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '20/15/10/5/2.5/1',
          'timeconstant': .003,
          },
    501: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '2/1.5/1/0',
          'timeconstant': .003,
          },
    502: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '2/1.5/1',
          'timeconstant': .03,
          },
    503: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': '/'.join([str(_*.25+.50) for _ in range(5)]),
          'SR': 2,
          'timeconstant': .03,
          },
    504: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': '/'.join([str(_*.25+.50) for _ in range(5)]),
          'SR': 2,
          'timeconstant': .003,
          },
    505: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 113,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': '/'.join([str(_*.25+.50) for _ in range(5)]),
          'SR': 2,
          'timeconstant': .1,
          },
    506: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': '/'.join([str(_/2) for _ in range(1,11)]),
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .1,
          'SR': 5,
          'timeconstant': .1,
          },
    507: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': 5,
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .025,
          'SR': '2/1.5/1/0',
          'timeconstant': .1,
          },
    508: {'Struct': 'Plusses',
          'Angle': 90,
          'Voltage': '/'.join([str(_/2) for _ in range(5,11)]),
          'Frequency': 17,
          'Temp': 15,
          'Preamp': False,
          'Rate': 8,
          'Dir': 'Up',
          'Limit': .1,
          'SR': 5,
          'timeconstant': .1,
          },
    }

info = pd.DataFrame(m_data).T
info.to_csv('mfn_info.csv')

# Install pyarrow for this to work
# info = info.reset_index()
# info.to_feather('measurement_info')