name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install software
        run: sudo apt install pandoc
        
      - name: Clone ana
        run: git clone https://gitlab.com/ody55eus/ana.git

      - name: Install ana
        run: cd ana && python -m pip install -e . && cd ..

      - name: Clone FORC data script
        run: cd docs/modules && git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/ody55eus/FORC-data.git forc && cd ../..

      - name: move OneNote exports
        run: mv source/onenote/html docs/_static/html && mv source/onenote/word docs/_static/word

      - name: Build the site
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "apt-get update -y && apt-get install -y dvipng man-db cm-super graphviz && python -m pip install recommonmark nbsphinx sphinx_rtd_theme"
          build-command: "sphinx-build -b html . _build"

      - name: Deploy site
        run: mv _build/html public

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
